### PR TITLE
Improve simhash performance

### PR DESCRIPTION
**Pull request by vadim-moz**

### CODE REVIEW

**Comment by b4hand** [comment]
Can you include some benchmark numbers showing the performance improvement? I'm skeptical of micro-optimizations without data.

**Comment by vadim-moz** [comment]
Do we have any micro-benchmark library "standard" in Moz c++?

**Comment by b4hand** [comment]
No, but I assumed you had written something that proved the performance improvement.

**Comment by vadim-moz** [comment]
Old code:
```
        mov     esi, 222222222
        mov     rcx, -1
        jmp     .L23
.L12:
        mov     rcx, rsi
        mov     r9, rax
        mov     r10, QWORD PTR [rax]
        and     ecx, 1
        cmp     rcx, 1
        sbb     rcx, rcx
        add     rax, 8
        or      rcx, 1
.L23:
        add     rcx, r10
        shr     rsi
        cmp     rax, r8
        mov     QWORD PTR [r9], rcx
        jne     .L12
```

New code:
```
        mov     edx, 222222222
        xor     al, al
.L8:
        mov     rcx, rdx
        shr     rdx
        and     ecx, 1
        add     QWORD PTR [rdi+rax*8], rcx
        add     rax, 1
        cmp     rax, 64
        jne     .L8
```

Beyond being shorter, the new code contains only one memory operation.

The idea of the code transformation is rather mathematical: instead of counting balance, count only one positive bits -- it is cleaner. The negative it difference between total and positive, and total can be taken out of the loop.

----------------

I tried to find microbenchmark. I tried [BenchPress](https://github.com/blockchaindev/benchpress), but it requires fresher C++ than we use (because of Jude). Google's microbenchmark is not headers only, I suspect, so I'm a bit reluctant.

**Comment by b4hand** [comment]
I was able to discern the mathematical transformation.

I agree that the assembly looks improved. I've used `cachegrind` before with good success, so you could try that. I'd also be satisfied with just running the code in a loop and taking timings.

Right now it's unclear that this code is a bottleneck and that speeding it up will improve performance at all.

I'd just like some real numbers that show this is a useful change as opposed to speculation and theory.

**Comment by vadim-moz** [comment]
> I was able to discern the mathematical transformation.

I never doubted that. My comment was mostly for documentation of change.

I added some benchmark:

```
no simhash:   486.243 ms
old simhash: 7171.212 ms
new simhash: 5167.793 ms
```

So we do have 30-40% performance gain on `simhash` calculation. (It leaves aside the question of how much simhash takes out of overall calculation. But, since we are realizing the lib as an open source, we can as well write it tightly for all use cases, not limiting to our.)

**Comment by b4hand** [comment]
Ok, I'm satisfied with those numbers. That's enough of a difference to make the change worthwhile. I just want to make sure that we're collected real timing data before making micro-optimizations that may not realize any actual change in performance.

LGTM

**Comment by vadim-moz** [comment]
Thank you!

**Pull request merged**
